# Generated by Django 4.2.1 on 2023-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(max_length=200),
        ),
    ]
